[package]
name = "macros"
version = "0.1.0"
edition = "2021"

[dependencies]
darling = "0.20.10"
paste = "1.0.15"
proc-macro-crate = "3.2.0"
proc-macro2 = "1.0.86"
proc-macro2-diagnostics = "0.10.1"
quote = "1.0.37"
syn = "2.0.79"

[lib]
proc-macro = true
